# Generated by Django 3.0.3 on 2020-02-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperatures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=15)),
                ('measureDate', models.DateField()),
                ('measureTimes', models.IntegerField()),
                ('temperature', models.CharField(max_length=5)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('recorderId', models.CharField(max_length=15)),
                ('remark', models.CharField(max_length=512)),
            ],
        ),
    ]
